### ISSUE TITLE
PHP 7 ToC not showing up

### ISSUE THREAD

**Issue by Sobak** [phpinternalsbook/PHP-Internals-Book#16]
Despite the (apparently) correct directives in `index.rst` table of contents for PHP 7 is not showing up, only header is.

**Comment by jpauli** [comment]
Launch ./build_html.sh , and it builds OK

**Comment by nikic** [comment]
This is intentional. The pages are all generated, but not linked from the TOC yet, as this content is still being active written.

**Comment by Sobak** [comment]
Okey, I think it wouldn't hurt to show them since they're prepended with appropriate warning, but since it's intentional, let's close that issue.
