### ISSUE TITLE
Epub version?

### ISSUE THREAD

**Issue by m1guelpf** [phpinternalsbook/PHP-Internals-Book#17]
Hi!
Is there any chance to get an EPUB version of the book?
Thank you!

**Comment by nikic** [comment]
Currently we only have HTML and PDF targets (though the PDF version is not published anywhere). But sphinx also supports epub, so it probably is not too hard.

**Comment by jelly** [comment]
@m1guelpf This would be as simple as
 ```
cd Book
make epub
```

I don't think it really deserves a new script

**Comment by jpauli** [comment]
@jelly :+1:   , closing
