### ISSUE TITLE
Adding testing section

### ISSUE THREAD

**Issue by SammyK** [phpinternalsbook/PHP-Internals-Book#19]
I've been working on a fairly lengthy blog post on testing PHP source. Do you think that belongs here? If so, I'll create a new section of the book instead of making it a blog post. :)

**Comment by nikic** [comment]
By testing I assume you mean phpt tests? If so, yes, I think that would be a great addition.

**Comment by SammyK** [comment]
Yes, `.phpt` tests based on [this talk](https://speakerdeck.com/sammyk/writing-tests-for-php-source-php-tek-2017) I gave recently. :)

Sounds good! I'll start working on this when I can get some time chunked out from client work. :)

**Comment by jpauli** [comment]
Ya, very nice idea.

There is a lot of content to add to this OpenSource book.
Basically, everything touching PHP's internal design or extension writing , so tests are definetly a great subject.

Please, target php7 (even though diffs with php5 are more than thin on such a subject).
Target /php7 in the source tree and do what you want in there respecting coding standards ;-)

**Comment by jpauli** [comment]
I started to write some content that would need a link to the testing chapter. If you could add it as well :-)

php7/extensions_design/php_function

**Comment by SammyK** [comment]
Hey @jpauli! I just pushed up a good start for the testing section - can you make sure I didn't screw anything up? I just now saw your comment about the php7 folder... which I totally didn't even do. Sorry about that! Let me know if you want me to make any changes or feel free to just go in there and do what you like. :)

**Comment by jpauli** [comment]
mmm yes we should push our content to php7/ , that's what we said so far not to modify the php5 content (located at /).  Can you update chapter into php7/ please ?

**Comment by jpauli** [comment]
mmm As that applies to both PHP 5 and PHP 7 , I think we can leave it here for the moment, and link to it. What you think @nikic  ?

**Comment by nikic** [comment]
We'll want to move it into php7 at some point (as I expect that we're going to split these more thoroughly, maybe move php5 off to a different subdomain), but for now we can leave it where it is.
