### ISSUE TITLE
Distinguish PHP 5 and PHP 7 stronger

### ISSUE THREAD

**Issue by nikic** [phpinternalsbook/PHP-Internals-Book#22]
Right now the title in the header only shows something like "USING THE PHP BUILD SYSTEM" -- but we have two of those now, one in PHP 5 and one in PHP 7. It's not clear which one you're on.

**Comment by jpauli** [comment]
I would suggest we target PHP 7 mainly.

Related https://github.com/phpinternalsbook/PHP-Internals-Book/issues/9

**Comment by nikic** [comment]
Yeah, probably not worth doing anything here, this will resolve itself once we move the PHP 5 stuff somewhere else (or drop it).

**Comment by jpauli** [comment]
That's what I was thinking and suggesting
