### ISSUE TITLE
Would really love some Hashtable docs for PHP7 section

### ISSUE THREAD

**Issue by jc21** [phpinternalsbook/PHP-Internals-Book#28]
Firstly, this guide is amazing. In truth though, the part I really need to learn is about the hashtable api for php7.

Appreciate your hard work on this.

**Comment by jpauli** [comment]
HashTables will come in next future.
@nikic should write the chapter ;-)  I could also push a starter

**Comment by jpauli** [comment]
Related to https://github.com/phpinternalsbook/PHP-Internals-Book/issues/68
