### ISSUE TITLE
Techniques for delaying zend extension unload are needlessly complicated

### ISSUE THREAD

**Issue by cataphract** [phpinternalsbook/PHP-Internals-Book#45]
There is a much simpler method to have the zend extension unloaded after the module: transfer the dl handle from the module to the zend extension. This requires only three lines of code:

```C
zend_module_entry *mod = zend_hash_str_find_ptr(
        &module_registry, "myext", sizeof("myext") - 1);
zend_register_extension(&zend_extension_entry, mod->handle);
mod->handle = NULL;
```

**Comment by jpauli** [comment]
This has been added to the relevant chapter.
Thx
