### ISSUE TITLE
zend_function documentation is not verbose enough

### ISSUE THREAD

**Issue by ace411** [phpinternalsbook/PHP-Internals-Book#63]
Hello. I recently noticed that the ```zend_function``` chapter of the book the purpose of which is detailing how functions work in PHP is incomplete. Seeing as to how pertinent the information about ```zend_function```s is, I kindly request that you update the section on the site.

**Comment by jpauli** [comment]
We have to update many things, but we mainly do that on our spare time , so not every day ... :-p

**Comment by ace411** [comment]
Oh, alright. I understand. Thanks for the swift response. I raised this issue because I want to create an extension that introduces some functional programming ideas to the PHP space. I realized that PHP function-related deficiencies in [php-cpp](http://www.php-cpp.com/) and [Zephir](https://zephir-lang.com/) are quite an encumbrance and decided to embark on creating a C-powered extension.
