### ISSUE TITLE
clone handler is outdated

### ISSUE THREAD

**Issue by 0mars** [phpinternalsbook/PHP-Internals-Book#66]
http://www.phpinternalsbook.com/classes_objects/custom_object_storage.html
current signature
zend_object *test_handler_clone(zval *zobject TSRMLS_DC)

checked against: PHP 7.2

**Comment by jpauli** [comment]
You are pointing the PHP 5 source tree, with a PHP 7 signature.
PHP 7 objects have not been detailed yet in the book.
