### ISSUE TITLE
Add links to blog posts about Zend compiler/executor

### ISSUE THREAD

**Issue by TysonAndre** [phpinternalsbook/PHP-Internals-Book#77]
e.g. http://nikic.github.io/2017/04/14/PHP-7-Virtual-machine.html and some others

Currently, http://www.phpinternalsbook.com/php7/zend_engine/zend_compiler.html and http://www.phpinternalsbook.com/php7/zend_engine/zend_executor.html are just a placeholder.

Adding a link to the blog post and a note that more details would be added later may help people who were looking for info

**Comment by nikic** [comment]
Sounds good, as those probably won't get written soon...
