### ISSUE TITLE
Enable HTTPS option for GitHub Pages

### ISSUE THREAD

**Issue by Krinkle** [phpinternalsbook/PHP-Internals-Book#99]
Both www and non-www result in a TLS certificate warning:

https://phpinternalsbook.com/php7/extensions_design/hooks.html

I think this is because the domain settings are still from before the github.io and Let's Encrypt support were introduced.

This should be fairly simple to fix, either in the repo settings or by updating the DNS pointer to reflect current requirements. See:
* https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain
* https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/securing-your-github-pages-site-with-https

**Comment by nikic** [comment]
In the settings it says:
> Unavailable for your site because your domain is not properly configured to support HTTPS

Probably needs some changes on the DNS side, though not sure which. I don't think I have access to this either, I think the domains belong to @ircmaxell.

**Comment by Krinkle** [comment]
Yeah, the IP addresses on that support page changed a few years ago when they moved from github.com to github.io and added Let's Encrypt support. I believe the domain currently points to github.com legacy IPs still, which actually seems to work still for basic HTTP, but no further.

**Comment by ircmaxell** [comment]
I made the change to the DNS, will wait for it to propagate and then see what happens from there.

**Comment by ircmaxell** [comment]
Closing as HTTPs appears to be working
